### ISSUE TITLE
数据表单里面的table组件image上传图片失败,使用的是七牛

### ISSUE THREAD

**Issue by ZimoBoy** [jqhph/dcat-admin#1214]
- Laravel Version: 8.0.x
- PHP Version: 7.4.13
- Dcat Admin Version: 2.0.23

### Description:

```
$form->table('intro', function (Form\NestedForm $form) {
                $form->image('icon', '图标')->saveFullUrl()->uniqueName()->autoUpload();
                $form->text('text', '内容');
            });
```

![image](https://user-images.githubusercontent.com/35425100/116490595-581ba900-a8ca-11eb-91b3-38128363243a.png)

```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'WU_FILE_0' for column 'id' at row 1 (SQL: update `kd_membership` set `id` = WU_FILE_0, `kd_membership`.`updated_at` = 2021-04-29 09:08:05 where `id` = 3) in file /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 678

#0 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\Database\Connection->runQueryCallback('update `kd_memb...', Array, Object(Closure))
#1 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Connection.php(503): Illuminate\Database\Connection->run('update `kd_memb...', Array, Object(Closure))
#2 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Connection.php(436): Illuminate\Database\Connection->affectingStatement('update `kd_memb...', Array)
#3 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2913): Illuminate\Database\Connection->update('update `kd_memb...', Array)
#4 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(841): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(936): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(851): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))
#7 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(783): Illuminate\Database\Eloquent\Model->save(Array)
#8 /var/www/kangdao/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(536): Illuminate\Database\Eloquent\Model->update()
#9 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): Dcat\Admin\Repositories\EloquentRepository->Dcat\Admin\Repositories\{closure}(Object(Illuminate\Database\MySqlConnection))
#10 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(371): Illuminate\Database\Connection->transaction(Object(Closure))
#11 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#12 /var/www/kangdao/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(539): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#13 /var/www/kangdao/vendor/dcat/laravel-admin/src/Form.php(816): Dcat\Admin\Repositories\EloquentRepository->update(Object(Dcat\Admin\Form))
#14 /var/www/kangdao/app/Admin/Controllers/MembershipController.php(33): Dcat\Admin\Form->update('3')
#15 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Admin\Controllers\MembershipController->vipUpdate('8', '3')
#16 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('vipUpdate', Array)
#17 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Admin\Controllers\MembershipController), 'vipUpdate')
#18 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route->runController()
#19 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Routing\Route->run()
#20 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/WebUploader.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\WebUploader->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/Session.php(12): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\Session->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/Permission.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\Permission->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/Bootstrap.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/Pjax.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/Authenticate.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#41 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/kangdao/vendor/dcat/laravel-admin/src/Http/Middleware/Application.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Http\Middleware\Application->handle(Object(Illuminate\Http\Request), Object(Closure), 'admin')
#48 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#51 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#52 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/kangdao/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/kangdao/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /var/www/kangdao/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /var/www/kangdao/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main}
```

**Comment by jqhph** [comment]
如果使用本地磁盘上传呢？

**Comment by ZimoBoy** [comment]
本地上传也是一样的

**Comment by ZimoBoy** [comment]
本地图片已经有了,就是还是会报这个sql的错

**Comment by jqhph** [comment]
并没有重新这个问题，建议重装一下并且重新发布文件清除浏览器缓存

**Comment by ZimoBoy** [comment]
重新装了发布了一下还是不行,最后用自定义上传接口搞定了

**Comment by hiccup711** [comment]
> 并没有重新这个问题，建议重装一下并且重新发布文件清除浏览器缓存

我今天也遇到一模一样的问题了，清除浏览器缓存后可以了，目前什么原因未知
