### ISSUE TITLE
表格组件使用model查询出现异常

### ISSUE THREAD

**Issue by dairidong** [jqhph/dcat-admin#1439]
- Laravel Version: 8.53.1
- PHP Version: 8.0.8
- Dcat Admin Version: 2.1.2-beta

### Description:
表格组件中使用模型的 `latest` 方法出现异常，只能使用 `orderBy` 方法
```
   $grid->model()->latest();
```

### Strace
```
local.ERROR: Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/blog/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php:190)
[stacktrace]
#0 /var/www/blog/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(190): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/var/www/blog/v...', 190)
#1 /var/www/blog/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(234): Dcat\\Admin\\Repositories\\EloquentRepository->Dcat\\Admin\\Repositories\\{closure}(Array, 0)
#2 /var/www/blog/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(195): Illuminate\\Support\\Collection->each(Object(Closure))
#3 /var/www/blog/vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php(161): Dcat\\Admin\\Repositories\\EloquentRepository->setSort(Object(Dcat\\Admin\\Grid\\Model))
#4 /var/www/blog/vendor/dcat/laravel-admin/src/Grid/Model.php(462): Dcat\\Admin\\Repositories\\EloquentRepository->get(Object(Dcat\\Admin\\Grid\\Model))
#5 /var/www/blog/vendor/dcat/laravel-admin/src/Grid/Model.php(393): Dcat\\Admin\\Grid\\Model->fetch()
#6 /var/www/blog/vendor/dcat/laravel-admin/src/Grid/Filter.php(650): Dcat\\Admin\\Grid\\Model->buildData()
#7 /var/www/blog/vendor/dcat/laravel-admin/src/Grid/Concerns/HasFilter.php(46): Dcat\\Admin\\Grid\\Filter->execute()
#8 /var/www/blog/vendor/dcat/laravel-admin/src/Grid.php(497): Dcat\\Admin\\Grid->processFilter()
#9 /var/www/blog/vendor/dcat/laravel-admin/src/Grid.php(1025): Dcat\\Admin\\Grid->build()
#10 /var/www/blog/vendor/dcat/laravel-admin/src/Grid.php(1119): Dcat\\Admin\\Grid->render()
#11 /var/www/blog/vendor/dcat/laravel-admin/src/Support/Helper.php(108): Dcat\\Admin\\Grid->__toString()
#12 /var/www/blog/vendor/dcat/laravel-admin/src/Layout/Column.php(107): Dcat\\Admin\\Support\\Helper::render(Object(Dcat\\Admin\\Grid))
#13 /var/www/blog/vendor/dcat/laravel-admin/src/Layout/Row.php(75): Dcat\\Admin\\Layout\\Column->render()
#14 /var/www/blog/vendor/dcat/laravel-admin/src/Layout/Content.php(281): Dcat\\Admin\\Layout\\Row->render()
#15 /var/www/blog/vendor/dcat/laravel-admin/src/Layout/Content.php(534): Dcat\\Admin\\Layout\\Content->build()
#16 /var/www/blog/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Dcat\\Admin\\Layout\\Content->render()
#17 /var/www/blog/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent(Object(Dcat\\Admin\\Layout\\Content))
#18 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(794): Illuminate\\Http\\Response->__construct(Object(Dcat\\Admin\\Layout\\Content), 200, Array)
#19 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(763): Illuminate\\Routing\\Router::toResponse(Object(Illuminate\\Http\\Request), Object(Dcat\\Admin\\Layout\\Content))
#20 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Router->prepareResponse(Object(Illuminate\\Http\\Request), Object(Dcat\\Admin\\Layout\\Content))
#21 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/WebUploader.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\WebUploader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#24 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/Session.php(12): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\Session->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/Permission.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\Permission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/Bootstrap.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\Bootstrap->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/Pjax.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\Pjax->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/Authenticate.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/blog/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/blog/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/blog/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#42 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/blog/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/blog/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/blog/vendor/dcat/laravel-admin/src/Http/Middleware/Application.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\\Admin\\Http\\Middleware\\Application->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'admin')
#49 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#51 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#52 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#53 /var/www/blog/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#54 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#55 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#66 /var/www/blog/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /var/www/blog/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /var/www/blog/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#72 /var/www/blog/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#73 /var/www/blog/public/index.php(59): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#74 {main}
"} 
```

**Comment by jqhph** [comment]
先用orderBy吧，我兼容下这个方法

**Comment by dairidong** [comment]
> 先用orderBy吧，我兼容下这个方法

好的，谢谢回复
