### ISSUE TITLE
不知道是不是最新版的问题

### ISSUE THREAD

**Issue by 8108905** [jqhph/dcat-admin#1881]
- Laravel Version: 9.19
- PHP Version: 8.1
- Dcat Admin Version: 2.2.2-bata

### Description:
不知道是不是最新版的原因；
已经设置laravel   'locale' => 'zh_CN', 

部分系统标题不是中文 例如 Admin.Menu admin.list | admin.refresh ，主要是 增加完Menu后无法修改删除，

Chrome F12看到 错误

menu:1067 TypeError: Cannot read properties of null (reading 'submit')
    at new e (DialogForm.js:23:25)
    at e.DialogForm (dcat-app.js:72:16)
    at menu:702:10
    at HTMLDocument.<anonymous> (menu:703:3)
    at e (eval at <anonymous> (vendors.min.js?v2.2.2-beta:2:1), <anonymous>:1:29453)
    at t (eval at <anonymous> (vendors.min.js?v2.2.2-beta:2:1), <anonymous>:1:29755)

**Comment by laradocs** [comment]
你是做升级操作还是第一次安装？

**Comment by 8108905** [comment]
首次安装laravel 以及 Dcat ，全是最新的 ！ 刚才通过官网更新教程 修复了问题 https://learnku.com/docs/dcat-admin/2.x/beta-version-update-log/9646
