### ISSUE TITLE
没有配置数据库连接的话composer install会提示如下

### ISSUE THREAD

**Issue by phpmac** [jqhph/dcat-admin#2141]
```

[previous exception] [object] (PDOException(code: 0): PDO::__construct(): Error while reading greeting packet. PID=32316 at /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:65)
[stacktrace]
#0 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): PDO->__construct('mysql:host=mari...', 'laravel', Object(SensitiveParameterValue), Array)
#1 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(83): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=mari...', 'laravel', 'laravel', Array)
#2 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(48): Illuminate\\Database\\Connectors\\Connector->tryAgainIfCausedByLostConnection(Object(PDOException), 'mysql:host=mari...', 'laravel', 'laravel', Array)
#3 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=mari...', Array, Array)
#4 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#5 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#6 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1339): call_user_func(Object(Closure))
#7 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1375): Illuminate\\Database\\Connection->getPdo()
#8 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(528): Illuminate\\Database\\Connection->getReadPdo()
#9 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(423): Illuminate\\Database\\Connection->getPdoForSelect(true)
#10 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(816): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#11 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(983): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#12 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(962): Illuminate\\Database\\Connection->tryAgainIfCausedByLostConnection(Object(Illuminate\\Database\\QueryException), 'select * from `...', Array, Object(Closure))
#13 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(785): Illuminate\\Database\\Connection->handleQueryException(Object(Illuminate\\Database\\QueryException), 'select * from `...', Array, Object(Closure))
#14 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#15 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2913): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#16 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2902): Illuminate\\Database\\Query\\Builder->runSelect()
#17 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3456): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#18 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2901): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#19 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(739): Illuminate\\Database\\Query\\Builder->get(Array)
#20 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(723): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#21 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(675): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#22 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/Extend/Manager.php(445): Illuminate\\Database\\Eloquent\\Model::all()
#23 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/Extend/Manager.php(85): Dcat\\Admin\\Extend\\Manager->settings()
#24 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/Extend/ServiceProvider.php(282): Dcat\\Admin\\Extend\\Manager->enabled('dcat-admin.goog...')
#25 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/Extend/ServiceProvider.php(292): Dcat\\Admin\\Extend\\ServiceProvider->enabled()
#26 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/Extend/ServiceProvider.php(88): Dcat\\Admin\\Extend\\ServiceProvider->disabled()
#27 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Dcat\\Admin\\Extend\\ServiceProvider->boot()
#28 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(240): Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}(Object(DcatAdmin\\GoogleAuth\\GoogleAuthServiceProvider), 'dcat-admin.goog...')
#29 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(59): Illuminate\\Support\\Collection->each(Object(Closure))
#30 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/Extend/Manager.php(74): Illuminate\\Support\\HigherOrderCollectionProxy->__call('boot', Array)
#31 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/AdminServiceProvider.php(248): Dcat\\Admin\\Extend\\Manager->boot()
#32 /Users/a/Downloads/fisheye/vendor/dcat/laravel-admin/src/AdminServiceProvider.php(113): Dcat\\Admin\\AdminServiceProvider->bootExtensions()
#33 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Dcat\\Admin\\AdminServiceProvider->boot()
#34 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#36 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#37 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#38 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1034): Illuminate\\Container\\Container->call(Array)
#39 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1015): Illuminate\\Foundation\\Application->bootProvider(Object(Dcat\\Admin\\AdminServiceProvider))
#40 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}(Object(Dcat\\Admin\\AdminServiceProvider), 15)
#41 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(1014): array_walk(Array, Object(Closure))
#42 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#43 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(263): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap(Object(Illuminate\\Foundation\\Application))
#44 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(447): Illuminate\\Foundation\\Application->bootstrapWith(Array)
#45 /Users/a/Downloads/fisheye/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(199): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#46 /Users/a/Downloads/fisheye/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#47 {main}
"} 

```

不知道是什么情况下需要这种，很容易存在后门之类的

**Comment by Hel5ing** [comment]
你好像一个🤡
